site_name: GNSS Java Documentation
site_description: Documentation for the GNSS Java project
repo_url: https://github.com/jdesbonnet/GNSS_Java
repo_name: jdesbonnet/GNSS_Java
docs_dir: docs
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - tables
  - fenced_code
  - codehilite
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - NMEA Guide: nmea.md
  - NTRIP & RTCM: ntrip-rtcm.md
  - API Reference: api.md
